config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'recipients/new'
  get 'recipients/create'
  get 'recipients/index'

  get 'users/index'
  get 'users/show'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'users/create'
  get 'users/edit'
  get 'users/update'
  get 'users/destroy'
  get 'users/following'
  get 'users/followers'

  get 'notifications/notify'
  get 'signup' => 'users#new'
  get 'task/create'
  post 'task/create' => 'task#create'

  get 'tasks/show'
  post 'tasks/sms' => 'tasks#sms'

  get 'task/edit_recipients', to: 'tasks#edit_recipients'
  post 'task/update_recipients', to: 'tasks#update_recipients'

  get 'twilio/voice'
  post 'twilio/voice' => 'twilio#voice'

  resources :users
  resources :sessions

  resources :tasks, :only => [:new, :create, :show, :edit, :update, :task_update_recipients, :task_edit_recipients]
  resources :recipients, :only => [:new, :create, :index]

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :ownerships, dependent: :destroy
  has_many :recipients, through: :ownerships

  validates  :activity, presence: true
  validates  :message, presence: true, length: { minimum: 1 }
  validates  :schedule_time, presence: true
  
  before_save :change_run_at

  # Sends a text message using secrets ENV and relays to twilio
  def send_text_messages
    phones = self.recipients.map(&:phone)
    twilio_phone = ENV["TWILIO_PHONE_NUM"]
    twilio_account_sid = Rails.application.secrets.twilio_account_sid
    twilio_auth_token = Rails.application.secrets.twilio_auth_token

    @client = Twilio::REST::Client.new twilio_account_sid, twilio_auth_token

    phones.each do |recipient_phone|
      @client.messages.create( 
        :from => twilio_phone,
      	:to   => recipient_phone,
      	:body => self.message
      )
    end
  end

  def delayed_job
    Delayed::Job.find(delayed_job_id)
  end

  def current_delayed_job  # What is the current DJ task is assigned to?
  end

  # Manual trigger. Assigns @task a DJ id and starts that instance.
  def schedule_sending_text # After user hits button on Task page
    job = self.delay(run_at: self.schedule_time).send_text_messages
    update_column(:delayed_job_id, job.id)
  end

  # Updates a task with new edit if a delayed_job is scheduled
  def change_run_at
    if schedule_time_changed? && !new_record? && !self.delayed_job_id.nil?
      delayed_job.update_column(:run_at, schedule_time)
    end
  end

  # Did that task send an SMS out yet?
  def delayed_job_attempts
    dj = self.delayed_job_id
    taskdj = Delayed::Job.find_by(:id => dj)
    if taskdj.attempts > 0
      return true
    end
  end

  # If task has NO delayed_job_id, show start button (task hasn't started yet)
  # Else if task has a DJ id, and attempts > 0 on that DJ_id, show start button (task ran already)
  # Else show cancel task and ***FAIL*** button (task is currently active and running)
  def find_task_status
    if self.delayed_job_id.nil?
      return "new"
    elsif self.delayed_job_id && delayed_job_attempts
      return "used"
    else
      return "active"
    end
  end

  # Trigger to stop active DJ task in daemon
  def kill_task

  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_filter :authorize, only: [:new]
  respond_to :html, :json

  def new  # page for CREATE
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      @task.ownerships.create(:task_id => @task.id)
      flash[:success] = "Task Scheduled!"
      redirect_to task_edit_recipients_path(:id => @task.id)
    else
      render 'new'
    end
  end



  def show  # page for sms
    @task = Task.find(params[:id])
    #pry 
  end

  # WHEN TESTING DELAYED JOBS, REMEMBER TO START DAEMON 
  # IN COMMAND LINE WITH bin/delayed_job start (or status, stop)
  # Run "rake jobs:clear" to clear all DJs
  # 
  # Run Delayed::Job.all in Rails Console to see DJs

  def sms  # Send SMS to task recipients
    @task = Task.find_by_id(params[:id])  # SMS get view

    # Action itself
    @task.schedule_sending_text  
    flash[:notice] = "Task scheduled!"
  end



  def edit # page for UPDATE
    @task = Task.find(params[:id])
    @recipients = @task.recipients
  end

  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(task_params)
      flash[:success] = "Task Updated!"
      redirect_to task_path(@task.id)
    else
      render :edit
    end
  end



  def edit_recipients # page for UPDATE_RECIPIENTS
    @task = Task.find(params[:id])
  end

  def update_recipients
    @task = Task.find(params[:id])

    # respond_to do |format|
    #   if @task.update_attributes(task_params)
    #     format.html { redirect_to user_path(current_user.id), notice: 'Recipient list updated!' }
    #   else
    #     format.html { render action: "edit_recipients" }
    #   end
    # end

    if @task.save
      flash[:success] = "Recipients added to task."
      redirect_to user_path(current_user.id)
    else
      render 'edit_recipients'
    end
  end


  private 

  def task_params
    params.require(:task).permit(:activity, :message, :phone,
                                 :schedule_time, :delayed_job_id, :completed,
                                 :recipient_ids => [])
  end
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>

  <%= error %>

  <div class="field">
    <p>
      <%= f.label :activity %>
      <%= f.text_field :activity, label: 'Activity' %><br />
    </p>
  </div>

  <div class="field">
    <p>
      <%= f.label :message %>
      <%= f.text_field :message %><br />
    </p>
  </div>

  <div class="field">
    <br />
    <p>
      <%= f.label :schedule_time, "Schedule Text Delivery Date" %>:
      <%= f.date_select :schedule_time %><br />

      <%= f.label :schedule_time, "Schedule Text Delivery Time" %>:
      <%= f.time_select :schedule_time %><br />
    </p>
  </div>

  <div class="form-actions">
    <br />
    <p>
      <%= f.submit "Create or Save Changes to Task" %>
    </p>
  </div>

<% end %>

app/views/tasks/_recipients_form.html.erb
<%= form_for @task do |f| %>

  <%= error %>

 <div class="recipient-fields">
    
    <p>Recipient List:</p>
    
    <p>
      <%= f.collection_check_boxes(:recipient_ids, current_user.recipients, :id, :name) %>
    </p>
  </div>

  <div class="form-actions">
    <br />
    <p>
      <%= f.submit "Submit" %>
    </p>
  </div>
<% end %>

app/views/tasks/_start_task_form.html.erb
<div>
  <%= form_for :task, url: {action: 'sms', params: {id: @task.id}} do |f| %>
          
    <%= f.hidden_field :phone, :value => @phones %>
    <%= f.hidden_field :message, :value => @task.message %>

    <p>
      <%= f.submit "Send Message and Start Timer Now!" %>
      </br>
      </br>
      <%= link_to 'Modify Task Details and Recipients', edit_task_path(@task.id) %>
      </br>
      <%= link_to 'Go Back', user_path(current_user.id) %>
    </p>

  <% end %>
</div>

app/views/tasks/create.html.erb
<h1>Task#create</h1>
<p>Find me in app/views/task/create.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Edit a Task</h1>

<%= render 'form' %>

<%= link_to 'Add or Remove Recipients', task_edit_recipients_path(:id => @task.id) %>
<% # SHOW TASK RECIPIENTS HERE %>
</br>
<%= link_to 'Go Back', task_path(@task.id) %>

app/views/tasks/edit_recipients.html.erb
<h1> Add recipients to your task!</h1>
<%= render 'recipients_form' %>
<%= link_to 'Back to Edit Task', edit_task_path(@task.id) %>
</br>
<%= link_to 'Back to Main Page', user_path(current_user.id) %>

app/views/tasks/index.html.erb
<h1>Tasks #index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>

<ul class="tasks">
  <% @tasks.each do |task| %>
    <div>
      <tr>
        <td><%= task.activity %></td>
        <td><%= task.message %></td>
        <td><%= task.schedule_time %></td>
    
            <% end %>
	  </tr>
    </div>
</ul>

app/views/tasks/new.html.erb
<h1>Schedule a New Task!</h1>

<%= render 'form' %>
<%= link_to 'Go Back', user_path(current_user.id) %>

app/views/tasks/show.html.erb
<h1>Task #show</h1>
<p>Button for Sending texts via app/views/tasks/show.html.erb</p>

<ul class="tasks">
    <div>
        <%= @task.activity %>
        </br>
        <%= @task.message %>
        </br>
        <%= @task.schedule_time %>
        </br>

        <h3>Being notified via SMS about your goal</h3>

        <% @task.recipients.each do |recipient| %>
          <%= recipient.name %>
          </br>
        <% end %>
    </div>
        

    </br>
    </br>
      <!-- IF task is already running, only show a cancel button (results in failure SMS notification) -->
        <%= render 'end_task_form' %>
      <!-- ELSE show button below to start task -->
        <%= render 'start_task_form' %>
</ul>