config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'recipients/new'
  get 'recipients/create'
  get 'recipients/index'

  get 'users/index'
  get 'users/show'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'users/create'
  get 'users/edit'
  get 'users/update'
  get 'users/destroy'
  get 'users/following'
  get 'users/followers'

  get 'notifications/notify'
  get 'signup' => 'users#new'
  get 'task/create'
  post 'task/create' => 'task#create'

  get 'tasks/show'
  post 'tasks/sms' => 'tasks#sms'

  get 'task/edit_recipients', to: 'tasks#edit_recipients'
  post 'task/update_recipients', to: 'tasks#update_recipients'

  get 'twilio/voice'
  post 'twilio/voice' => 'twilio#voice'

  resources :users
  resources :sessions

  resources :tasks, :only => [:new, :create, :show, :edit, :update, :task_update_recipients, :task_edit_recipients]
  resources :recipients, :only => [:new, :create, :index]

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :tasks
	has_many :recipients

	validates :name, presence: true, length: { minimum: 5 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
					  format: { with: VALID_EMAIL_REGEX },
					  uniqueness: { case_sensitive: false }
	validates :phone, presence: true, length: { minimum: 7 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks
    @user_recipients = @user.recipients
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(session[:user_id]), notice: "Thank you for signing up!"
    else
      render 'new'
    end
  end

  private 

  def user_params
    params.require(:user).permit(:email, :name, :phone, :admin, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/followers.html.erb
<h1>Users#followers</h1>
<p>Find me in app/views/users/followers.html.erb</p>

app/views/users/following.html.erb
<h1>Users#following</h1>
<p>Find me in app/views/users/following.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
    <div>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.admin %></td>
	  </tr>
    </div>
    <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up A New User</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form_control' %>
      </div>
      <div>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form_control' %>
	    </div>
      <div>
        <%= f.label :phone %>
        <%= f.text_field :phone, class: 'form_control' %>
      </div>
      <div>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form_control' %>
      </div>
      <div>
        <%= f.label :password_confirmations %>
        <%= f.password_field :password_confirmations, class: 'form_control' %>
      </div>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Welcome <%= @user.name %>!</h1>


<div>
	<h3>Here are your accountability buddies:</h3>

	  <%= link_to "Add somebody to keep you accountable!", new_recipient_path, class: "btn btn-lg btn-primary" %>

	<ul class="recipients">
	  <% @user_recipients.each do |recipient| %>
	    <div>
	      <tr>
	        <td><%= recipient.name %></td>
		  </tr>
	    </div>
	    <% end %>
	</ul>
</div>

<div>  
	<h3>Here are all your scheduled goals:</h3>

		  <%= link_to "Set a new goal!", new_task_path, class: "btn btn-lg btn-primary" %>
	</br>
	</br>
	<ul class="tasks">
	  <% @tasks.each do |task| %>
	    <div>
	      <tr>
	        <h3>Goal:</h3>
	        <td><%= link_to task.activity, task_path(task.id), class: "btn btn-lg btn-warning" %></td>

	        <td>
	          <h3>SMS:</h3>
	            <p><%= task.message %></p>
	        </td>

	        <td>
	        <h3>Text Outbound at:</h3>
	        <%= task.schedule_time %>
	        </td>
			
			<h3>Keeping you accountable for this task:</h3>
			<% task.recipients.each do |recipient| %>
			  <div>
			  <%= recipient.name %>
			  </div>
			<% end %>
			</br>
			</br>
		  </tr>
	    </div>
	    <% end %>

	    <!-- Impliment Task status. Began? Complete? New? -->

	</ul>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>