config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get 'recipients/new'
  get 'recipients/create'
  get 'recipients/index'

  get 'users/index'
  get 'users/show'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'users/create'
  get 'users/edit'
  get 'users/update'
  get 'users/destroy'
  get 'users/following'
  get 'users/followers'

  get 'notifications/notify'
  get 'signup' => 'users#new'
  get 'task/create'
  post 'task/create' => 'task#create'

  get 'tasks/show'
  post 'tasks/sms' => 'tasks#sms'

  get 'task/edit_recipients', to: 'tasks#edit_recipients'
  post 'task/update_recipients', to: 'tasks#update_recipients'

  get 'twilio/voice'
  post 'twilio/voice' => 'twilio#voice'

  resources :users
  resources :sessions

  resources :tasks, :only => [:new, :create, :show, :edit, :update, :task_update_recipients, :task_edit_recipients]
  resources :recipients, :only => [:new, :create, :index]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Texting</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-default navbar-static-top">
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "Sample Rails Texting App", root_path, :class => "brand" %>
				<div class='session-controls'>
					<% if current_user %>
						<%= link_to "Log Out", logout_path, :class => 'btn btn-danger btn-mini' %>						Logged in as <%= current_user.email %>.
					<% else %>
						<div class="btn-group">
							<%= link_to "Sign Up", signup_path, :class => "btn btn-mini" %>
							<%= link_to "Log In", login_path, :class => "btn btn-mini" %>
						</div>
					<% end %> 
				</div>
			</div>
		</div>
	</div>

	
<div class="row">
	<div class="span4">
		<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, id: "flash_#{name}" %>
		<% end %>
	</div>
</div>

<%= yield %>

</body>
</html>